const API=(window.OFFICIAL_CARS_CONFIG?.API_BASE||'').replace(/\/$/,'');
let db={dealers:[],vehicles:[],sourceMeta:{}};const app=document.querySelector('#app');document.querySelector('#year').textContent=new Date().getFullYear();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dealer=id=>db.dealers.find(d=>d.id===id)||{name:'Participating Dealer',borough:'NYC',address:'New York'};
function img(v){return v.images?.[0]?`<img loading="lazy" src="${esc(v.images[0])}" alt="${esc(v.year+' '+v.make+' '+v.model)}" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'">`:''}
function card(v){const d=dealer(v.dealerId);return `<article class="card" onclick="detail('${esc(v.id)}')"><div class="carpic"><span class="tag">${esc(v.tag||'Dealer inventory')}</span>${img(v)}<div class="fallback" style="display:${v.images?.[0]?'none':'grid'}">🚗</div>${v.images?.length?`<span class="photoCount">${v.images.length} photos</span>`:''}</div><div class="cardbody"><h3>${esc(v.year)} ${esc(v.make)} ${esc(v.model)}</h3><div class="meta">${esc(v.type||'Vehicle')} • ${Number(v.miles||0).toLocaleString()} miles • ${esc(d.borough||'')}</div><div class="specs">${v.engine?`<span>${esc(v.engine)}</span>`:''}${v.transmission?`<span>${esc(v.transmission)}</span>`:''}${v.drivetrain?`<span>${esc(v.drivetrain)}</span>`:''}</div><div class="price">$${Number(v.price||0).toLocaleString()}</div><div class="dealer">${esc(d.name)}</div></div></article>`}
function home(){app.innerHTML=`<div class="page-in"><section class="hero"><div><div class="eyebrow">NYC • PARTICIPATING DEALERS • LIVE INVENTORY</div><h1>Every car.<br><span>One destination.</span></h1><p>Official Cars makes it easier to discover participating dealer inventory, compare real listing details and jump directly to the dealer's original vehicle page.</p><div class="actions"><a class="btn primary" href="#/cars">Browse cars</a><a class="btn secondary" href="#/partner">Partner with us</a></div></div><div class="hero-card"><div class="eyebrow" style="color:#53b7ff">SEARCH LIVE INVENTORY</div><div class="search"><input id="heroQ" placeholder="Make, model, SUV, price…"><button onclick="goSearch()">Search</button></div><div class="chips"><button onclick="location.hash='/cars?type=SUV'">SUVs</button><button onclick="location.hash='/cars?type=Sedan'">Sedans</button><button onclick="location.hash='/cars?q=Toyota'">Toyota</button><button onclick="location.hash='/cars?q=Jeep'">Jeep</button></div></div></section><section class="stats"><div><b>${db.vehicles.length}</b><span>vehicles loaded</span></div><div><b>${db.dealers.length}</b><span>dealer locations</span></div><div><b>${db.vehicles.reduce((n,v)=>n+(v.images?.length||0),0)}</b><span>listing photos</span></div></section><section class="section"><div class="eyebrow">FEATURED INVENTORY</div><h2>Real dealer listings.</h2><div class="grid">${db.vehicles.slice(0,9).map(card).join('')||'<div class="empty">The inventory API is not connected yet.</div>'}</div><p class="disclosure">Official Cars is a vehicle discovery/referral platform. Vehicles are sold by participating dealers. Official Cars may receive compensation for qualifying referrals. Confirm availability, pricing, fees and vehicle details directly with the dealer.</p></section></div>`}
function cars(){const p=new URLSearchParams(location.hash.split('?')[1]||'');app.innerHTML=`<section class="section page-in"><div class="eyebrow">INVENTORY</div><h2>Find your next car.</h2><div class="filters"><input id="q" placeholder="Search make, model, VIN, stock #, dealer…" value="${esc(p.get('q')||'')}"><select id="type"><option value="">All types</option><option>SUV</option><option>Sedan</option><option>Crossover</option><option>Mini-Van</option><option>Hatchback</option><option>Cargo Mini-Van</option><option>Wagon</option></select><select id="max"><option value="">Any price</option><option value="7000">Under $7k</option><option value="12000">Under $12k</option><option value="18000">Under $18k</option><option value="25000">Under $25k</option><option value="35000">Under $35k</option></select><select id="borough"><option value="">All locations</option>${[...new Set(db.dealers.map(d=>d.borough).filter(Boolean))].map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div id="grid" class="grid"></div></section>`;if(p.get('type'))document.querySelector('#type').value=p.get('type');['q','type','max','borough'].forEach(x=>document.querySelector('#'+x).oninput=renderCars);renderCars()}
function renderCars(){const q=document.querySelector('#q').value.toLowerCase(),t=document.querySelector('#type').value,m=Number(document.querySelector('#max').value||0),b=document.querySelector('#borough').value;const arr=db.vehicles.filter(v=>{const d=dealer(v.dealerId),txt=`${v.make} ${v.model} ${v.year} ${v.type} ${v.stock||''} ${v.vin||''} ${d.name}`.toLowerCase();return(!q||txt.includes(q))&&(!t||v.type===t)&&(!m||Number(v.price)<=m)&&(!b||d.borough===b)});document.querySelector('#grid').innerHTML=arr.map(card).join('')||'<div class="empty">No matching vehicles.</div>'}
function dealers(){app.innerHTML=`<section class="section page-in"><div class="eyebrow">NETWORK</div><h2>Participating dealers.</h2><div class="dealergrid">${db.dealers.map(d=>`<article class="dealerbox"><span class="eyebrow">${esc(d.borough||'NYC')}</span><h3>${esc(d.name)}</h3><p>${esc(d.address||'')}<br>${esc(d.phone||'')}<br><b>${db.vehicles.filter(v=>v.dealerId===d.id).length}</b> vehicles</p><a class="btn secondary" href="#/cars">View inventory</a></article>`).join('')||'<div class="empty">No dealers loaded yet.</div>'}</div></section>`}
function how(){app.innerHTML=`<section class="section page-in"><div class="eyebrow">HOW IT WORKS</div><h2>A simpler car-shopping flow.</h2><div class="steps"><article class="step"><b>01</b><h3>Discover</h3><p>Search participating dealer inventory in one place.</p></article><article class="step"><b>02</b><h3>Compare</h3><p>Review the actual listing information we imported from the dealer's vehicle page.</p></article><article class="step"><b>03</b><h3>Connect</h3><p>Open the original dealer listing and contact the seller directly. Official Cars does not sell the vehicle.</p></article></div></section>`}
function partner(){app.innerHTML=`<section class="section page-in"><div class="partner"><div><div class="eyebrow" style="color:#53b7ff">FOR DEALERS</div><h2>Bring your inventory to Official Cars.</h2><p>Use an authorized feed, CSV, API or dealer portal. We can track inventory freshness, clicks and qualified leads.</p></div><form class="form" onsubmit="partnerSubmit(event)"><input required name="business" placeholder="Dealership / business"><input required name="email" type="email" placeholder="Business email"><input name="feed" placeholder="Authorized inventory feed URL"><button class="btn primary">Request partnership</button><small id="pm"></small></form></div></section>`}
function partnerSubmit(e){e.preventDefault();document.querySelector('#pm').textContent='Request received in this demo. Connect email/CRM before launch.'}
function detail(id){const v=db.vehicles.find(x=>x.id===id);if(!v)return;const d=dealer(v.dealerId);const x=document.createElement('dialog');const main=v.images?.[0]||'';const spec=(label,val)=>val?`<div><b>${label}</b><span>${esc(val)}</span></div>`:'';x.innerHTML=`<div class="modal"><button class="x" onclick="this.closest('dialog').close()">×</button><div class="modalGrid"><div class="modalPhoto">${main?`<img src="${esc(main)}" alt="${esc(v.year+' '+v.make+' '+v.model)}">`:'<div class="fallback">🚗</div>'}</div><div class="modalInfo"><div class="eyebrow">${esc(v.condition||'DEALER LISTING')}</div><h2>${esc(v.year)} ${esc(v.make)} ${esc(v.model)}</h2><div>${esc(v.type||'Vehicle')} • ${Number(v.miles||0).toLocaleString()} miles • ${esc(d.name)}</div><div class="modalPrice">$${Number(v.price||0).toLocaleString()}</div><div class="modalSpecs">${spec('Engine',v.engine)}${spec('Transmission',v.transmission)}${spec('Drivetrain',v.drivetrain)}${spec('Fuel',v.fuel)}${spec('Exterior',v.exteriorColor)}${spec('Interior',v.interiorColor)}${spec('Stock #',v.stock)}${spec('VIN',v.vin)}${spec('Fuel economy',v.mpg)}</div>${v.description?`<p>${esc(v.description)}</p>`:''}<p class="disclosure">Vehicle information is imported from the dealer listing and may change. Confirm current availability, pricing, fees and specifications directly with the dealer.</p><a class="btn primary" href="${esc(v.url||'#')}" target="_blank" rel="noopener">Open original dealer listing ↗</a></div></div></div>`;document.body.appendChild(x);x.showModal();x.addEventListener('close',()=>x.remove())}
function goSearch(){location.hash='/cars?q='+encodeURIComponent(document.querySelector('#heroQ').value)}
async function load(){try{const r=await fetch(API+'/api/public',{cache:'no-store'});if(!r.ok)throw new Error('API');db=await r.json()}catch(e){db={dealers:[],vehicles:[],sourceMeta:{error:'API unavailable'}}}route()}
function route(){const path=location.hash.slice(1)||'/';if(path.startsWith('/cars'))cars();else if(path==='/dealers')dealers();else if(path==='/how')how();else if(path==='/partner')partner();else home();window.scrollTo({top:0,behavior:'smooth'})}
window.addEventListener('hashchange',route);load();
